### ISSUE TITLE
Link for the documentation not working.

### ISSUE THREAD

**Issue by Utwo** [adonisjs/adonis-websocket#1]
I follow the link from readme.md to adonisjs official documentation, but seems like the page was removed.
This is the link: [http://adonisjs.com/docs/3.1/websockets]( http://adonisjs.com/docs/3.1/websockets)

**Comment by niallobrien** [comment]
I'm guessing they're work-in-progress.

**Comment by thetutlage** [comment]
Should be working now

**Comment by Utwo** [comment]
Wow, it's awesome! Thank you very much! There is almost no advantage on using Laravel over Adonis right now.
