### ISSUE TITLE
No compatible version found: uws@^0.13.0

### ISSUE THREAD

**Issue by benxaamin** [adonisjs/adonis-websocket#10]
Node v7.7.4 (npm v4.1.2)

When create a new adonis project from cli I am getting this error

xaamin$ npm install
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/nulldata/.nvm/versions/node/v7.7.4/bin/node" "/Users/nulldata/.nvm/versions/node/v7.7.4/bin/npm" "install"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: uws@^0.13.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.14.1
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'adonis-websocket'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nulldata/Xaamin/NodeJS/headhunt-api/npm-debug.log

Some help is welcome. Thanks.

**Comment by RomainLanz** [comment]
Hey @benxaamin !

This was a problem with `uws` that have remove all versions in the NPM registry.
@thetutlage has managed to fix this in the latest release (`1.0.4`).

* https://github.com/uWebSockets/uWebSockets/issues/551

**Comment by benxaamin** [comment]
Thanks. This morning I can completed the AdonisJS framework installation.
