### ISSUE TITLE
Get Socket By User ID and Emit

### ISSUE THREAD

**Issue by samuelcesc** [adonisjs/adonis-websocket#14]
How do I get a list of sockets without pulling them as the pull function leads to untracking? Just want to get a list of sockets by user id and emit to those sockets.

**Comment by thetutlage** [comment]
You can use the `get` method and pass it the user id

**Comment by samuelcesc** [comment]
It worked! Thanks!

**Comment by tpharaoh** [comment]
Can I see a sample of how you did this?

**Comment by samuelcesc** [comment]
Hi @tpharaoh , here it is:
```
const user_id = 1  //as an example
const channel = Ws.channel('/my-channel-url')
var socket = channel.presence.get(user_id)
var socket_id = socket[0].socket.id
```
Hope this helps.

Cheers!

**Comment by tpharaoh** [comment]
Thanks @samuelcesc 

I am really excited about the possibilities here, but I guess the presence isn't working in v4 yet, so I gotta wait.

**Comment by llampwall** [comment]
is presence ever going to be added to v4? and if not, is there some way to implement it ourselves?
