### ISSUE TITLE
Websocket without adonis-websocket-client

### ISSUE THREAD

**Issue by dspangenberg** [adonisjs/adonis-websocket#15]
Hi,

I'm trying to connect from a VueJS app (with MetinSeylan/Vue-Socket.io) to the web socket. But channels are not supported by socket.io on the client side. How can I response to events or use the presence feature in an AdonisJs app without a channel? Something like
```
Ws.channel('inquiries', 'InquiriesController').middleware('auth')
```
in socket.js does not work.

Regards,
Danny

**Comment by thetutlage** [comment]
Any specific reasons you don't want to use `adonis-websocket-client`?

**Comment by dspangenberg** [comment]
Not really, the idea I have not come and the "Using with VueJS"  I noticed too late.  Have you a hint, how to integrate adonis-websocket-client with vuex?

**Comment by thetutlage** [comment]
Frankly saying there is no out of the box solution of Vue or Vuex. Here is a bare-bones example of integrating it with Vue https://github.com/adonisjs/adonis-websocket-client#using-with-vuejs.

Best I can do share a working example with Vue and if you can take it over from there and mold it as per your use case

**Comment by dspangenberg** [comment]
Thanks anyway. I will try to adapt MetinSeylan/Vue-Socket.io with adonis-websocket-client in a quiet hour.

**Comment by eventdift** [comment]
this might help with vuejs , there has been an update on how plugins can be attached to the vue 2.0 

const wsVuePlugin = [
]

const url = 'http://localhost:3000'
wsVuePlugin.install= (Vue,data)=>{
    Vue.prototype.$io = data.ws(data.url);
}

Vue.use(wsVuePlugin,{ws:ws,url:url})
