### ISSUE TITLE
Support for Adonis v4

### ISSUE THREAD

**Issue by ntvsx193** [adonisjs/adonis-websocket#26]
Any plan for release Adonis v4?

**Comment by thetutlage** [comment]
Yes will be soon.

**Comment by ntvsx193** [comment]
Any progress?
It will be great if you make first release.
Thx

**Comment by stecapra** [comment]
+1

**Comment by firsyura** [comment]
@thetutlage maybe you need a help to the migration?

**Comment by firsyura** [comment]
@thetutlage Can you help me with new implementation of Session?
Check my changes here - https://github.com/adonisjs/adonis-websocket/compare/develop...firsyura:develop

**Comment by ntvsx193** [comment]
@thetutlage Can you say the approximate date of implementation? I need told to my leadership date of full migrate to v4. Thx

**Comment by thetutlage** [comment]
@ntvsx193 Sorry, not sure about the date right now. 

Also it's festival session in my country, so kind of stuck into other stuff. Give me a week, I will go through the required changes, make some plan and then let you know.

Ohh man, some should hire me for full time development on AdonisJs now

**Comment by thetutlage** [comment]
@firsyura Will look into it soon and let you know.

**Comment by dv336699** [comment]
@ntvsx193 don't want to sound rude or anything, but if you need the feature, why not support @thetutlage instead of asking stuff for free?

Ask your "leadership" to pay for it.

Thanks

**Comment by thetutlage** [comment]
@firsyura @diego-vieira Just an update.

I have started working on it and will be out soon, also using Redis to scale the websockets on multiple servers

**Comment by firsyura** [comment]
@thetutlage Cool. If you need a helping hand feel free to message me

**Comment by RomainLanz** [comment]
Closing this.
Feel free to continue the discussion here https://github.com/adonisjs/discussion/issues/51
