### ISSUE TITLE
Is it suppose to work on version 4 also ?

### ISSUE THREAD

**Issue by barak-haviv** [adonisjs/adonis-websocket#34]
I followed the instruction and got errors the first one
Error: Cannot find module 'adonis-fold'

And then
RuntimeException: E_INVALID_SERVICE_PROVIDER: WsProvider must extend base service provider class

**Comment by RomainLanz** [comment]
Hey @barak-haviv! 👋 

Please, read https://github.com/adonisjs/discussion/issues/51
