### ISSUE TITLE
Connections from SocketIO?

### ISSUE THREAD

**Issue by bostinait** [adonisjs/adonis-websocket#44]
Just starting out with Adonis (I've used Laravel for a good many years) and I'm liking what I am seeing so far.

I am trying to integrate Adonis into an existing project that already has a subsystem (written in python) that communicates via SocketIO. 

Can this provider accept connections generated via SocketIO? And if so, how can it be achieved.

Thank you in advance!

**Comment by thetutlage** [comment]
In short No. SocketIo has their own logic on top of Websockets and Adonis has their own. You can read more about the protocol here https://github.com/adonisjs/adonis-websocket-protocol
