### ISSUE TITLE
one mistake in websocket documentation   

### ISSUE THREAD

**Issue by kamal-chagam** [adonisjs/adonis-websocket#45]
![image](https://user-images.githubusercontent.com/6966631/38163003-0e923c72-350a-11e8-9a28-f86b4d39988b.png)

  is the the following correct? in the above example ? 
`@adonisjs/websocket-client/clusterPubSub` 

isn't the following to replace above?

`@adonisjs/websocket/clusterPubSub`   

I may be wrong too, please correct me

thank you .. you did awesome work

**Comment by ntvsx193** [comment]
Fixed in https://github.com/adonisjs/docs/pull/261

**Comment by kamal-chagam** [comment]
thanks
