### ISSUE TITLE
presence

### ISSUE THREAD

**Issue by tpharaoh** [adonisjs/adonis-websocket#46]
I followed your tutorial on websockets and this line:
```
constructor ({ socket, request, presence }) {
    presence.track(socket,socket.currentUser.Id,{})
}
```

gets:
```
presence.track(socket,socket.currentUser.Id,{})
             ^

TypeError: Cannot read property 'track' of undefined
```

**Comment by thetutlage** [comment]
Where did you followed the tutorial?

**Comment by tpharaoh** [comment]
Your videos for 3.2, but I realis it’s not same in 4.

**Comment by thetutlage** [comment]
Yeah the presence is not in 4 as of now. Will be added soon.

**Comment by tpharaoh** [comment]
Excuse my ignorance, I am trying to make a way to send a message to a user server one to one.
I know I can pass auth into my WS and get this.auth.user.id

But, if a method returns something, I'd like to push a message to user. Now lets assume user initiates an action, leaves the page, but still within site. When the action is done, I want to send result.

Each page load the socket.id changes. So the following method I guess would be hard to know
socket.emit('id', socket.id)

I can see an option where a middleware would update most recent socketid, but wouldn't that needlessly increase load? I know Presence would accomplish that, but is there something I am missing

**Comment by tpharaoh** [comment]
I guess that doesn't work either because to doesn't exist
chatChannel.to([]).emit('greet', 'Hello world')

**Comment by tpharaoh** [comment]
to anyone following this question, emitTo() was added 3 days ago, it covers part of the above needs... as long as you track the IDs elsewhere, for now

**Comment by thetutlage** [comment]
Can you tell me a use case, where you have to track the IDS?

**Comment by tpharaoh** [comment]
Well, when user clicks a link it initiates a back end process for the user,
when completed I want to push to the user the result.

I am a laravel forge user, and when creating a server I can move around the
site, change pages freely, when server is provisioned I am notified.

I am working on some IOT provisioning. When firmware provisioned the
configuration is returned from API its added to DB, and then push data to
user.

**Comment by thetutlage** [comment]
If user (who clicks the link) is connected to the socket. Then why don't you send the socketId as part of HTTP request and then use that id to fire a websocket event

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by twigs67** [comment]
Any update on presence being added to 4.1?

**Comment by annymosse** [comment]
how can i get the clients ids ,and how can i use .emitTo() where i don't know which id for each client?, hopefully if there is someone know more than the documentation help me (us) to dive deeply
```js
//start/socket.js

const Ws = use('Ws')

var clients=[]

Ws.channel('chat', ({ socket,request,auth}) => {
  socket.on('message',function(message){
    clients.indexOf(socket.id)<0?clients.push(socket.id):null
    console.log(clients);
    socket.broadcastToAll('message', message)
    // socket.emitTo('message', message,auth.user.socketID)
  })
  socket.on('close', () => {
    clients.splice(clients.indexOf(socket.id),1)
    console.log(clients);
  })
})
```
currently i made that code to solve `clients ids` ,Is there a better solution?
and is there an idea how to attach the `socket.id` to auth user like : `auth.user.socketID`
without sending the socket id with the data message ?

**Comment by annymosse** [comment]
Any update on presence being added to 4.1?

**Comment by rbarbosas** [comment]
Any update on presence being added to 4.1? ²

**Comment by ArturMassaro** [comment]
Any update on presence being added to 4.1?³
