### ISSUE TITLE
wsServer is not a function

### ISSUE THREAD

**Issue by mtnptrsn** [adonisjs/adonis-websocket#47]
I have:
1. Installed the websocket package with `adonis install @adonisjs/websocket --yarn`
2. Added `'@adonisjs/websocket/providers/WsProvider'` to providers
3. Added `.wsServer()` to the bootstrap chain (after `new Ignitor(require('@adonisjs/fold')).appRoot(__dirname)`)

When trying to start the server i get:
```
TypeError: (intermediate value).appRoot(...).wsServer is not a function
```

Am I doing something wrong? I am using adonuxt if that makes a difference.

**Comment by mtnptrsn** [comment]
Sorry. I just needed to update my packages.

**Comment by nwashangai** [comment]
Thanks @mtnptrsn for sharing, the solution you provided just solved my different problem
