### ISSUE TITLE
blocked cross-origin

### ISSUE THREAD

**Issue by izacximenes** [adonisjs/adonis-websocket#49]
![deepin screenshot_selecionar area_20180411142740](https://user-images.githubusercontent.com/33349688/38633792-15af8484-3d97-11e8-9942-b7a197c6ad0c.png)

**Comment by RomainLanz** [comment]
Hey @izacximenes (let start by being polite...) 👋 

1. Your message is a simple picture in a non-english language. Could be a little bit more descriptive.

2. Search about CORS within Google and you will find your solution.

**Comment by izacximenes** [comment]
@RomainLanz I am trying to make a connection with websocket, but it only returns cors error

**Comment by thetutlage** [comment]
Closing since not actionable
