### ISSUE TITLE
Channels list and usage?

### ISSUE THREAD

**Issue by ghost** [adonisjs/adonis-websocket#51]
#question

Hello, 

Im building a chat application with Adonis, but I couldn't figure out how to:

1. Dynamically create new chat rooms
2. List all active rooms
3. List all connected users within a room
4. Presence

I would appreciate your assistance on this as I already chose adonis framework for my project and I wouldn't want to go back to socket.io again. :)

Thank you very much in advance.
Looking forward to hearing from you soon! @thetutlage

**Comment by thetutlage** [comment]
What you are asking for is to draw you an architecture. For these of questions, prefer using the forum or discord server.

**Comment by ghost** [comment]
No. What im asking is if there are any built in methods like in socket.io for instance, where i can simply ask for rooms length or even iterate through socket connections from a room id.

If not, are there any future plans for that in Adonis?

Thank you! @thetutlage

**Comment by tpharaoh** [comment]
I think that wasn’t made in version 4

**Comment by thetutlage** [comment]
@coderbro9 

The biggest challenge I see everyone having is, thinking the entire world revolves around Express or socket.io. Adonis documentation doesn't talk about `rooms` at all. 

If you will read the documentation carefully https://adonisjs.com/docs/4.1/websocket-philosophy#_channels_topics. You will get the idea on how channels and topics work and how you can use them to your best.

Ofcourse, if you struggle at any specific point, feel free to ask questions around it

**Comment by thetutlage** [comment]
Closing since not actionable
