### ISSUE TITLE
Channels have no subscriptions when called from adonis-scheduler task

### ISSUE THREAD

**Issue by lukasrakauskas** [adonisjs/adonis-websocket#52]
I've tried using adonis-websocket package with [adonis-scheduler](https://www.npmjs.com/package/adonis-scheduler) and when I tried getting channels subscriptions it showed none. But it was shown when called from HTTP contoller.

Here is an example code. Everything else is used as in chat example from docs.
https://gist.github.com/lukasrakauskas/9bd6cc1095943a80465e59b5761f0f0f

**Comment by thetutlage** [comment]
When you run your process using `adonis-scheduler`, how do you expect your clients to join channels?

**Comment by lukasrakauskas** [comment]
Well I thought channels data was supposed to be the same application wide. My bad then.

**Comment by thetutlage** [comment]
It’s share application wide. But when you start 2 processes, then they are 2 different applications.

**Comment by thetutlage** [comment]
Closing since not actionable
