### ISSUE TITLE
Question about GraphQL Subscriptions and Adonis WebSocket

### ISSUE THREAD

**Issue by yariksav** [adonisjs/adonis-websocket#56]
It's difficult to explain problem, but I will try:

I have tried to realize GraphQL Subscriptions (througs apollo subscriptions-transport-ws) with AdonisJS framework and WebSockets, and it works, but:

When I connect SubscriptionServer through adonis-websocket WS server - I works, but with some troubles, adonis-websocket send ping packets and after timeouts and limits it disconnect connections with clients. (it is correct logic, but GraphQL SubscriptionServer cannot work with it)

I had to connect GraphQL SubscriptionServer through **new** WebSocket server, it works fine, but ONLY if I disable Adonis WebSocket. Because two WS servers in one http server don't work correctly [see issue](https://github.com/websockets/ws/pull/885#issue-187590719)

Therefore if I will use GraphQL Subscriptions, I cannot use Adonis WebSockets.. and same to backward... 

I ask only your opinion, guys, and maybe some solution
Thank YOU!

**Comment by thetutlage** [comment]
Hello @yariksav 

Sorry for getting late on this. Ideally it's not possible to make Adonis work with `apollo subscriptions` seamlessly. 

Adonis adds a lot to the Websocket protocol, and I am not sure if `apollo subscriptions` uses vanilla Websocket connection.

I have plans to make GraphQL as the first class citizen in 5.0 and then I can re-visit `apollo subscriptions` and see if a clean integration is possible.
