### ISSUE TITLE
PM2 support

### ISSUE THREAD

**Issue by Ruby184** [adonisjs/adonis-websocket#58]
## Why this feature is required?
I want to run adonis production application using websockets with PM2 (http://pm2.keymetrics.io).
The problem is the inter-process broadcast messaging cannot be done just like this:
```javascript
const cluster = require('cluster')
// this condition is false for every process run by pm2 because pm2 is the master daemon process
if (cluster.isMaster) {
  require('@adonisjs/websocket/clusterPubSub')()
  return
}
```
So after some research i found that i can use PM2 Programmatic API and included message bus to send messages between processes managed by pm2. See example (http://pm2.keymetrics.io/docs/usage/pm2-api/#send-message-to-process).

I wrote a simple PM2 module which uses `pm2.launchBus` and `pm2.sendDataToProcessId` methods to accomplish the same thing as `require('@adonisjs/websocket/clusterPubSub')()` does. The main part:

```javascript
pm2.launchBus((err, bus) => {
  // listen for adonis ClusterHop event type
  bus.on('adonis:hop', ({ process: proc, data }) => {
    pm2.Client.getProcessByName(proc.name, (err, workers) => {
      workers.forEach((worker) => {
        if (worker.pm2_env.pm_id === proc.pm_id) {
          return
        }
        pm2.sendDataToProcessId(worker.pm2_env.pm_id, {
          type: 'adonis:hop', // event type is required to distinguish from other PM2 events
          topic: data.handle, // topic is required, just use handle
          data // event data for adonis ClusterHop - contains handle, topic and payload props
        }, (err, res) => {
          //
        })
      })
    })
  })
})
```

The problem is the difference between the format of messages that adonis messaging `ClusterHop` and PM2 bus implementation expects.

| Messaging  | Adonis ClusterHop  | PM2 bus |
| ------------- | ------------- | ------------- |
| `process.send(packet)` | `const packet = JSON.stringify({ handle, topic, payload })` | `const packet = { type: 'adonis:hop', data: { handle, topic, payload } }` |
| `process.on('message', (packet) => {}`  | `const message = JSON.parse(packet)` | `const message = packet.data // if packet.type === 'adonis:hop'` |

## Possible solutions
- modify the current ClusterHop implementation to support both pm2 and pure adonis cluster i.e. use the PM2 bus one
- add conditional PM2 implementation (check for `process.env.pm_id`) and fall back to current implementaion

## Are you willing to work on it with little guidance?
Sure, i can send a PR for either first or second solution. Just tell me which one is better for you. Maybe out of the box support for pm2 module would be nice too. I can publish and maintain one by myself if you are not interested.

Thanks.

**Comment by thetutlage** [comment]
Woohoo, this is awesome.

I am happy with the implementation that checks for `process.env.pm_id` and then changes the behaviour accordingly.

Feel free to write the code and share the PR 😄

**Comment by RomainLanz** [comment]
Closing in favor of the PR.
