### ISSUE TITLE
JWT Auth in websockets 

### ISSUE THREAD

**Issue by vaneetjoshi** [adonisjs/adonis-websocket#62]
hi i am trying to implement jwt authentication in web sockets but i am not able to get auth object in web socket controller please guide me

# Error
     {topic: "notifications", message: "Unexpected token       await auth.authenticator('jwt').check();"}

# sockets.js

    Ws.channel('notifications', 'NotificationController').middleware(['client_jwt_auth'])

# NotificationController.js

      'use strict'
      const objUser = use('App/Models/User');

      class NotificationController {
        constructor({ socket, request, auth }) {
          this.socket = socket
          this.request = request
          // await auth.authenticator('jwt').check();
          // const User = await auth.getUser()
          try {
            await auth.authenticator('jwt').check();
            console.log('Auth to use jwt socket');
          } catch (error) {
            console.log(error)
          }
          // console.log('Orders Connected');
          console.log('user joined with ' + socket.id + ' socket id in group ' + socket.topic)
        }
        
      }

      module.exports = NotificationController

# client side javascript code

    let nws = null
    nws = adonis.Ws().withJwtToken(JWToken).connect()
    // nws = adonis.Ws().connect()

    nws.on('open', () => {
        console.log('WS Connected')
        subscribeToChannel()
    })

    nws.on('error', (error) => {
        console.log('Error in WS : ' + error)
    })

    function subscribeToChannel() {
        const notifications = nws.subscribe('notifications')

        notifications.on('error', (error) => {
            console.log(error)
        })

        notifications.on('message', (message) => {
            console.log(message)
        })
    }

**Comment by thetutlage** [comment]
Inside your `NotificationController` constructor, you are using the keyword `await`. However `await` can only be used when top level function is `async` (Learn more about async/await separately).

There is no need to manually add the authentication, use one of the inbuilt methods https://adonisjs.com/docs/4.1/websocket-server#_registering_middleware

**Comment by vaneetjoshi** [comment]
i want to send some data to users at the time of connecting to socket matching their user id from database please guide how can i do that
