### ISSUE TITLE
Access user model even if ws middleware doesnt have auth

### ISSUE THREAD

**Issue by edge-rps** [adonisjs/adonis-websocket#70]
So the issue I have is need access the this.auth.user is my websocket controller but for some reason the websocket channel requires the auth middleware attached to do so. It's a chat application so I need the users to receive chat messages but need to be logged in to send messages.

PS: im using jwt and lucid-mongo

**Comment by thetutlage** [comment]
@rykerparker From where the user will then come from?

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
